#!/usr/bin/env sh

# clone all submodules
git submodule update --init --recursive

ln -sv ~/.dotfiles/kitty ~/.config/kitty
ln -sv ~/.dotfiles/polybar ~/.config/polybar
ln -sv ~/.dotfiles/rofi ~/.config/rofi
ln -sv ~/.dotfiles/kmonad ~/.config/kmonad
ln -sv ~/.dotfiles/swaylock ~/.config/swaylock
ln -sv ~/.dotfiles/hypr ~/.config/hypr

ln -sv ~/.dotfiles/.xinitrc ~/.xinitrc
ln -sv ~/.dotfiles/.Xmodmap ~/.Xmodmap
ln -sv ~/.dotfiles/.Xresources ~/.Xresources
ln -sv ~/.dotfiles/.p10k.zsh ~/.p10k.zsh

# shell settings
ln -sv ~/.dotfiles/zsh/.zshrc ~/.zshrc
ln -sv ~/.dotfiles/zsh/.oh-my-zsh ~/.oh-my-zsh

ln -sv ~/.dotfiles/ranger ~/.config/ranger

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# install zsh powerlevel10k theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
# plugins
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# byobu settings
ln -sv ~/.dotfiles/byobu ~/.config/byobu

# nvim settings
ln -sv ~/.dotfiles/nvim ~/.config/nvim

# vim settings -----------------
ln -sv ~/.dotfiles/vim ~/.vim

# vundle cloning
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# vim package manager - vundle plugins install
vim +BundleInstall
#additionally install ripgrep, fzf

# YCM install
/usr/bin/python3 ~/.dotfiles/vim/bundle/YouCompleteMe/install.py
# ------------------------------

#lighter way to get gruvbox git clone https://github.com/morhetz/gruvbox.git ~/.vim/pack/default/start/gruvbox

# Arch packages
: '
ranger ueberzug
zathura


'
