#!/usr/bin/env sh

# kitty settings
ln -sv ~/.dotfiles/.config/kitty ~/.config/kitty

# shell settings
ln -sv ~/.dotfiles/zsh/.zshrc ~/.zshrc
ln -sv ~/.dotfiles/zsh/.oh-my-zsh ~/.oh-my-zsh

# install zsh powerlevel10k theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
# plugins
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# byobu settings
ln -sv ~/.dotfiles/byobu ~/.byobu

# nvim settings
ln -sv ~/.dotfiles/.config/nvim ~/.config/nvim

# vim settings -----------------
ln -sv ~/.dotfiles/vim ~/.vim

# clone all submodules
git submodule update --init --recursive

# vim package manager - vundle plugins install
vim +BundleInstall

# YCM install
/usr/bin/python3 ~/.dotfiles/vim/bundle/YouCompleteMe/install.py
# ------------------------------

